version: '3'

services:
  tfl-journey-to-sql:
    build:
      context: .
      dockerfile: Dockerfile
    env_file: 
      - .env
    volumes:
      - ./data/input:/data/input
      - ./data/output:/data/output
      - ./data/meta:/data/meta
